# Generated by Django 3.1.1 on 2020-09-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device', models.IntegerField(primary_key=True, serialize=False, verbose_name='device')),
                ('name', models.CharField(max_length=50, verbose_name='meno')),
                ('tms', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'db_table': 'sg_device',
                'ordering': ('device',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place', models.IntegerField(primary_key=True, serialize=False, verbose_name='place')),
                ('name', models.CharField(max_length=50, verbose_name='meno')),
                ('tms', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'sg_place',
                'ordering': ('place',),
            },
        ),
        migrations.CreateModel(
            name='RecordSumDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('event_in', models.IntegerField(verbose_name='event in')),
                ('event_out', models.IntegerField(verbose_name='event out')),
                ('event_tag', models.IntegerField(verbose_name='event tag')),
            ],
            options={
                'db_table': 'sg_recordsumday',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='RecordSumHour',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('event_in', models.IntegerField(verbose_name='event in')),
                ('event_out', models.IntegerField(verbose_name='event out')),
                ('event_tag', models.IntegerField(verbose_name='event tag')),
            ],
            options={
                'db_table': 'sg_recordsumhour',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='RecordSumMonth',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('event_in', models.IntegerField(verbose_name='event in')),
                ('event_out', models.IntegerField(verbose_name='event out')),
                ('event_tag', models.IntegerField(verbose_name='event tag')),
            ],
            options={
                'db_table': 'sg_recordsummonth',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='RecordSumYear',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('event_in', models.IntegerField(verbose_name='event in')),
                ('event_out', models.IntegerField(verbose_name='event out')),
                ('event_tag', models.IntegerField(verbose_name='event tag')),
            ],
            options={
                'db_table': 'sg_recordsumyear',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.IntegerField(choices=[(1, 'CUSTOMER IN'), (2, 'CUSTOMER OUT'), (3, 'CASH OPEN'), (4, 'CASH CLOSE'), (5, 'CASHIER ALARM'), (6, 'CASHIER ALARM'), (7, 'TAG ALARM'), (8, 'GATE SHIELDING'), (9, 'OCTOPUS ALARM'), (90, 'T-CON REQUEST'), (99, 'TEST')], verbose_name='event')),
                ('tms', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('device', models.ForeignKey(db_column='device', on_delete=django.db.models.deletion.CASCADE, to='app.device', verbose_name='device')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
                'db_table': 'sg_record',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='device',
            name='place',
            field=models.ForeignKey(db_column='place', on_delete=django.db.models.deletion.CASCADE, to='app.place', verbose_name='place'),
        ),
    ]
